### ISSUE TITLE
Unable to find the server at oauth2.googleapis.com

### ISSUE THREAD

**Issue by xStevex** [taers232c/GAM-Scripts3#16]
During the running GetSharedWithDomainDriveACLs.py:
```
Got 296 Files fortest@test.com...
Getting files for test@test.com...
Got 0 Files for test@test.com...
Getting files for test@test.com...
Got 2 Files for test@test.com...
```
After some times I have this error:
```
Traceback (most recent call last):
  File "httplib2\__init__.py", line 1366, in _conn_request
  File "httplib2\__init__.py", line 1142, in connect
  File "socket.py", line 962, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "google_auth_httplib2.py", line 119, in __call__
  File "httplib2\__init__.py", line 1724, in request
  File "httplib2\__init__.py", line 1444, in _request
  File "httplib2\__init__.py", line 1373, in _conn_request
httplib2.error.ServerNotFoundError: Unable to find the server at oauth2.googleapis.com

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gam\__main__.py", line 57, in <module>
  File "gam\__main__.py", line 52, in main
  File "gam\__init__.py", line 12369, in ProcessGAMCommand
  File "gam\__init__.py", line 3324, in printDriveFileList
  File "gam\__init__.py", line 1291, in buildDriveGAPIObject
  File "gam\__init__.py", line 1260, in buildGAPIServiceObject
  File "google\oauth2\service_account.py", line 429, in refresh
  File "google\oauth2\_client.py", line 303, in jwt_grant
  File "google\oauth2\_client.py", line 264, in _token_endpoint_request
  File "google\oauth2\_client.py", line 213, in _token_endpoint_request_no_throw
  File "google\oauth2\_client.py", line 189, in _perform_request
  File "gam\transport.py", line 82, in wrapped_request_method
  File "gam\transport.py", line 95, in __call__
  File "google_auth_httplib2.py", line 126, in __call__
google.auth.exceptions.TransportError: Unable to find the server at oauth2.googleapis.com
[20948] Failed to execute script '__main__' due to unhandled exception!
```
How could I fix it?

**Comment by taers232c** [comment]
This is a networking issue on your computer.
What does this show: gam checkconn

Ross
----
Ross Scroggs
***@***.***

**Comment by xStevex** [comment]
Yes, you are right. It was my network issue.
